// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/examples/dynamic":{"path":"examples/dynamic","id":"docs/examples/dynamic","parentId":"DocLayout"},"docs/examples/loading":{"path":"examples/loading","id":"docs/examples/loading","parentId":"DocLayout"},"docs/examples/locale":{"path":"examples/locale","id":"docs/examples/locale","parentId":"DocLayout"},"docs/examples/simple":{"path":"examples/simple","id":"docs/examples/simple","parentId":"DocLayout"},"docs/examples/event":{"path":"examples/event","id":"docs/examples/event","parentId":"DocLayout"},"docs/examples/graph":{"path":"examples/graph","id":"docs/examples/graph","parentId":"DocLayout"},"docs/examples/theme":{"path":"examples/theme","id":"docs/examples/theme","parentId":"DocLayout"},"docs/examples/api":{"path":"examples/api","id":"docs/examples/api","parentId":"DocLayout"},"docs/examples/svg":{"path":"examples/svg","id":"docs/examples/svg","parentId":"DocLayout"},"docs/examples/gl":{"path":"examples/gl","id":"docs/examples/gl","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'C:/Users/aarafeh/Repos/echarts-for-react/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'C:/Users/aarafeh/Repos/echarts-for-react/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'C:/Users/aarafeh/Repos/echarts-for-react/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/examples/dynamic': React.lazy(() => import(/* webpackChunkName: "docs__examples__dynamic.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/dynamic.md')),
'docs/examples/loading': React.lazy(() => import(/* webpackChunkName: "docs__examples__loading.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/loading.md')),
'docs/examples/locale': React.lazy(() => import(/* webpackChunkName: "docs__examples__locale.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/locale.md')),
'docs/examples/simple': React.lazy(() => import(/* webpackChunkName: "docs__examples__simple.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/simple.md')),
'docs/examples/event': React.lazy(() => import(/* webpackChunkName: "docs__examples__event.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/event.md')),
'docs/examples/graph': React.lazy(() => import(/* webpackChunkName: "docs__examples__graph.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/graph.md')),
'docs/examples/theme': React.lazy(() => import(/* webpackChunkName: "docs__examples__theme.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/theme.md')),
'docs/examples/api': React.lazy(() => import(/* webpackChunkName: "docs__examples__api.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/api.md')),
'docs/examples/svg': React.lazy(() => import(/* webpackChunkName: "docs__examples__svg.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/svg.md')),
'docs/examples/gl': React.lazy(() => import(/* webpackChunkName: "docs__examples__gl.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/gl.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'C:/Users/aarafeh/Repos/echarts-for-react/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
