// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/dynamic.md?type=frontmatter';
import { demoIndex as dmi0 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/dynamic.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/loading.md?type=frontmatter';
import { demoIndex as dmi1 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/loading.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/locale.md?type=frontmatter';
import { demoIndex as dmi2 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/locale.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/simple.md?type=frontmatter';
import { demoIndex as dmi3 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/simple.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/event.md?type=frontmatter';
import { demoIndex as dmi4 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/event.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/graph.md?type=frontmatter';
import { demoIndex as dmi5 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/graph.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/theme.md?type=frontmatter';
import { demoIndex as dmi6 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/theme.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/api.md?type=frontmatter';
import { demoIndex as dmi7 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/api.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/svg.md?type=frontmatter';
import { demoIndex as dmi8 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/svg.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/gl.md?type=frontmatter';
import { demoIndex as dmi9 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/gl.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/index.md?type=frontmatter';
import { demoIndex as dmi10 } from 'C:/Users/aarafeh/Repos/echarts-for-react/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/examples/dynamic': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/dynamic.md?type=text'),
  },
  'docs/examples/loading': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/loading.md?type=text'),
  },
  'docs/examples/locale': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/locale.md?type=text'),
  },
  'docs/examples/simple': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/simple.md?type=text'),
  },
  'docs/examples/event': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/event.md?type=text'),
  },
  'docs/examples/graph': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/graph.md?type=text'),
  },
  'docs/examples/theme': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/theme.md?type=text'),
  },
  'docs/examples/api': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/api.md?type=text'),
  },
  'docs/examples/svg': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/svg.md?type=text'),
  },
  'docs/examples/gl': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/examples/gl.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/aarafeh/Repos/echarts-for-react/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
