// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/aarafeh/Repos/echarts-for-react/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
